// backend/modules/itam/models/asset.model.js

class Asset {
    constructor(assetName, assetTypes, manufacturer, model, serialNumber, status, location, owner, department, purchaseDate, warrantyInformation, configurationDetails, relatedAssets) {
        this.assetId = null; // Unique identifier - will be generated by database
        this.assetName = assetName;
        this.assetTypes = assetTypes; // e.g., ['hardware', 'laptop']
        this.manufacturer = manufacturer;
        this.model = model;
        this.serialNumber = serialNumber;
        this.status = status; // e.g., in use, available, retired
        this.location = location;
        this.owner = owner;
        this.department = department;
        this.purchaseDate = purchaseDate;
        this.warrantyInformation = warrantyInformation;
        this.configurationDetails = configurationDetails; // e.g., OS, software versions
        this.relatedAssets = relatedAssets; // e.g., connected peripherals
    }
}

module.exports = Asset;